In [ ]:
dict1={}
print(dict1)

{}


In [ ]:
dict1={}
dict1['1']=1
dict1['2']=2
dict1[3]="three"
dict1[2]=[1,2,3,4]

print(dict1)
print(dict1.keys())

{'1': 1, '2': 2, 3: 'three', 2: [1, 2, 3, 4]}
dict_keys(['1', '2', 3, 2])


In [ ]:
t1=(1,2,3)

l1=[1,2,3]
print(l1)

[1, 2, 3]


In [ ]:
t1=(1,2,3)
t2=('a','b','c')

t3=t1+t2
print(t3)

(1, 2, 3, 'a', 'b', 'c')


In [ ]:
s1=set()
print(s1)


set()


In [ ]:
s1=set([1,2,3,3,3])
print(s1)

{1, 2, 3}


In [ ]:
name = input('Please give your name: ')
print(name)

Please give your name: Lydia
Lydia


In [ ]:
a=int(input("Please give the first number"))
b = int(input("Please give the second number"))

print(a*b)

Please give the first number10
Please give the second number10
100


In [ ]:
d2 = {}

key1=int(input("Key 1: "))
key2=int(input("Key 2: "))

d2[key1]=2*key1
d2[key2]=2*key2
#d2={1:2, 2:4}

print(d2)


Key 1: 1
Key 2: 2
{1: 2, 2: 4}


In [ ]:
list1 = ['hello', 'world']
print(list1)

for i in list1:
  print(i)

print(len(list1))


['hello', 'world']
hello
world
2


In [ ]:
for i in range(0, 10, 1):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
i=0
for i in range(0, len(list1)):
  print(list1[i])

hello
world


In [ ]:
for letter in 'predictiveanalytics':
  if letter=='e' or letter=='s':
    continue
  print(letter)



str1='predictiveanalytics'
i=0
while i<len(str1):
  if str1[i]=='e' or str1[i]=='s':
    i+=1
    continue
  i+=1
  print(str1[i])


In [ ]:
l1 = [1,2,3,4,5,6,7,8,9,10]
#Print only the values at the indices that are even -- 0,2,4,6,8
#Use a for loop

for i in range(0,len(l1)):
  if i%2==0:
    print(l1[i])


1
3
5
7
9


In [ ]:
for i in range(0,3):
  print("Hello World")

print("While")
count =0
while count<3:
  print("Hello World")
  count+=1




In [ ]:
num=4

if num%2==0:
  print("Even number")
elif num%2==1:
  print("Odd number")
else:
  print("Never comes here")


Even number


In [ ]:
def isEven(num):
  if num%2==0:
    return True
  elif num%2==1:
    return False 

print(isEven(10))
print(isEven(11))

True
False


In [ ]:
def cube(y):
  return y*y*y

cube(3)

27

In [ ]:
g = lambda y:y*y*y

In [ ]:
def square(x):
  return x*x


print(square(5))

25


In [ ]:
g=lambda x:x*x
g(5)

25

In [ ]:
y=8
z=lambda x:x*y
print(z(6))

48


In [ ]:
keywords = ['hello', 'I', 'am', 'fine', 'but', 'fine', 'is', 'fine', 'hello', 'to', 'you', 'fine']

In [ ]:

dictionary1={}
for key in keywords:
  try:
    dictionary1[key]+=1
  except:
    dictionary1[key]=1

print(dictionary1)

{'hello': 2, 'I': 1, 'am': 1, 'fine': 4, 'but': 1, 'is': 1, 'to': 1, 'you': 1}


In [ ]:
keywords = ['hello', 'I', 'am', 'fine', 'but', 'fine', 'is', 'fine', 'hello', 'to', 'you', 'fine']
dictionary1={}
for key in keywords:
  if key in dictionary1.keys():
    dictionary1[key]+=1
  else:
    dictionary1[key]=1
print(dictionary1)

{'hello': 2, 'I': 1, 'am': 1, 'fine': 4, 'but': 1, 'is': 1, 'to': 1, 'you': 1}


In [ ]:
type(dictionary1)

dict

#### Numpy 

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print('A is of type:', type(a))
print(a)

A is of type: <class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14,
15, 16]])

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b1=10*a
b2=np.multiply(10,a)
print(a)
print(b1)
print(b2)

c=np.log(a)
d=np.sqrt(a)
e=a**2  #This squares the value.
print(c)
print(d)
print(e)

[1 2 3 4 5 6]
[10 20 30 40 50 60]
[10 20 30 40 50 60]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 1  4  9 16 25 36]


In [ ]:
#Generate random distributions
a = np.random.uniform(50, 150, 10)  #Between 50-150, generate 10 variables from uniform
b = np.random.standard_normal(10)   #With mean 0 and standard deviation 1 
print(a)
print(b)

[113.0334884   54.51321927 145.26920878  74.43328686 143.4301836
  54.52765362  96.8717555   96.70898962  88.43146802 123.19783281]
[ 0.83165093  0.06342236 -1.11620395  0.05896959  0.16111082  0.99869784
 -1.21940383  1.44370769 -0.49400153 -0.82816044]


#### Pandas


In [ ]:
import pandas as pd

data={'Name':['John', 'William', 'Ian', 'Noah'],'Age':['12', '15', '13', '12']} 
df = pd.DataFrame(data)

print(df)

In [ ]:
import pandas as pd
data={'Name': ['John', 'William', 'Ian', 'Noah'], 'Age':[12, 15, 13, 12]}
df = pd.DataFrame(data)
print(df)

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving nba.csv to nba.csv


In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col="Name")
first=data["Age"]
print(first)

Name
Avery Bradley    25.0
Jae Crowder      25.0
John Holland     27.0
R.J. Hunter      22.0
Jonas Jerebko    29.0
                 ... 
Shelvin Mack     26.0
Raul Neto        24.0
Tibor Pleiss     26.0
Jeff Withey      26.0
NaN               NaN
Name: Age, Length: 458, dtype: float64


In [ ]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col= "Name")
#data.loc pulls a row 
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
print(first)
print(second)

Team        Boston Celtics
Number                   0
Position                PG
Age                     25
Height                 6-2
Weight                 180
College              Texas
Salary         7.73034e+06
Name: Avery Bradley, dtype: object
Team        Boston Celtics
Number                  28
Position                SG
Age                     22
Height                 6-5
Weight                 185
College      Georgia State
Salary         1.14864e+06
Name: R.J. Hunter, dtype: object


In [ ]:
#read 23rd row
import pandas as pd
data = pd.read_csv("nba.csv", index_col= "Name")
test = data.iloc[23]
print(test)


Team        Brooklyn Nets
Number                 11
Position                C
Age                    28
Height                7-0
Weight                275
College          Stanford
Salary         1.9689e+07
Name: Brook Lopez, dtype: object


In [ ]:
#Count the number of rows
data['Team'].count()

457

In [ ]:
#Maximum age of the players in this dataset
data['Age'].max()

In [ ]:
#What are the teams that have players from Stanford
data['Team'][data['College']=='Stanford']

In [ ]:
#Group the rows based on a certain common attribute 
#What are the teams that are there in our dataset

data.groupby(['Team']).groups.keys() 

In [ ]:
#How many players are there from each team in our dataset 
data.groupby('Team')['Age'].count()

Team
Atlanta Hawks             15
Boston Celtics            15
Brooklyn Nets             15
Charlotte Hornets         15
Chicago Bulls             15
Cleveland Cavaliers       15
Dallas Mavericks          15
Denver Nuggets            15
Detroit Pistons           15
Golden State Warriors     15
Houston Rockets           15
Indiana Pacers            15
Los Angeles Clippers      15
Los Angeles Lakers        15
Memphis Grizzlies         18
Miami Heat                15
Milwaukee Bucks           16
Minnesota Timberwolves    14
New Orleans Pelicans      19
New York Knicks           16
Oklahoma City Thunder     15
Orlando Magic             14
Philadelphia 76ers        15
Phoenix Suns              15
Portland Trail Blazers    15
Sacramento Kings          15
San Antonio Spurs         15
Toronto Raptors           15
Utah Jazz                 15
Washington Wizards        15
Name: Age, dtype: int64